/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` / `next build`.
// It's included here so the project type-checks out of the box; Next.js
// will overwrite it on first run, which is expected.
